### PR TITLE
CI

### PR DESCRIPTION
**Pull request by bkmgit**
Use GitHub actions to test Ubuntu and MacOS builds.

### CODE REVIEW

**Comment by bkmgit** [comment]
If this is ok, lines 5 and 7 in .github/workflows/test.yml should have "ci" changed to "master". Tests pass at https://github.com/bkmgit/RE-flex/tree/ci

**Comment by genivia-inc** [comment]
Thanks for contributing. But why is this needed? The project does not depend on the OS.

**Comment by bkmgit** [comment]
This is related to https://github.com/Genivia/RE-flex/issues/142#issuecomment-1213364222 - want to be sure builds will occur on supported architectures.

**Comment by genivia-inc** [comment]
Are you sure? #142 is about static versus dynamic libraries on Linux/Unix and MacOS. Has nothing to do with OS/architectures.

**Comment by bkmgit** [comment]
This would allow for testing that dynamically linked library builds and works on MacOS and that changes do not break this.

**Comment by genivia-inc** [comment]
I appreciate your effort, but with all the changes in services (Travis CI no longer free and LGTM moved to a different analysis paradigm), I've looked into GitHub C/C++ CI actions and used that instead. It builds and runs tests.

**Pull request closed without merging**
