### PR TITLE
Fix yyset_lineno() Flex compatibility wrappers

### PR DESCRIPTION
**Pull request by dnicolodi**
Only superficially tested, but this fixes the problems reported in #88 for me.

### CODE REVIEW

**Comment by genivia-inc** [comment]
Looks good to me.

**Comment by genivia-inc** [comment]
Let me also update v2.1.5 right away with this change.

**Comment by dnicolodi** [comment]
There may still be an issue somewhere. My application is not segfaulting in `reflex::AbstractMatcher::lineno()` because `this` is a NULL pointer... I am looking at it.

**Comment by genivia-inc** [comment]
Strange. The changes should be alright though, as they're aligned with the other methods and functions. Thanks for your quick response!

**Comment by dnicolodi** [comment]
Is it possible that a `FlexLexer` object exists in a state where the `Matcher` is NULL? What I am doing in my code is equivalent to instantiating a lexer and immediately calling the `lineno(n)` method on it.

**Comment by dnicolodi** [comment]
Yes, apparently this is what is happening. How does the lexer object acquire a matcher?

**Comment by genivia-inc** [comment]
The matcher is assigned when the lexer's `lex` (or `yylex`) function is invoked. In the initial state only the input can be assigned, but no other properties of the matcher. Different matchers are associated with start condition states, while sharing the same input etc. Therefore, the lexer sets the proper matcher(s) at scan time.

**Comment by dnicolodi** [comment]
I see. If I understand correctly the matcher is not static, thus there must already be a way to tell the next matcher at what line the previous one left the input. Is it so? I am trying to get familiar with the code...

**Comment by dnicolodi** [comment]
How would you implement a scanner that start counting the input lines from a number different from 1?

**Comment by genivia-inc** [comment]
Correct. The matcher(s) are not static, but the patterns are because patterns are read-only. The generated scanner source code (e.g. `lex.yy.cpp`) shows how this is done:
~~~
  static const reflex::Pattern PATTERN_INITIAL(reflex_code_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
    YY_USER_INIT
  }
~~~
A simple trick/workaround is to initialize the matcher is to present it without any input:
~~~
Lexer lexer;
lexer.lex(reflex::Input()); // force matcher init using empty input (produces EOF, be mindful of any wrap() when set)
lexer.in(file); // assign new input, e.g. from a file
~~~
In reentrant/bison-bridge "flex code" this becomes:
~~~
yyFlexLexer lexer(reflex::Input());
lexer.yylex(); // force init with EOF
yyrestart(&lexer, file); // reentrant yyrestart(): assign new input, e.g. from a file
~~~

**Comment by dnicolodi** [comment]
Doesn't `yyrestart()` or equivalently calling `lexer.in()` reset the input line number? I would expect this to be the case, and thus this workaround does not quite work for setting the initial line number.

**Comment by genivia-inc** [comment]
I don't see why setting the line number after `yyrestart()` will not work, or am I missing something? The first part of the code is to associate a matcher with the lexer.

In most scenarios that I am familiar with, e..g when implementing `#line`, the `yyset_lineno()` function will be called on demand while scanning input, and not before `yylex()` is called for the first time. When a `#line` is encountered the specified file name is set and `yyset_lineno()` is called with the specified line number.

**Comment by dnicolodi** [comment]
I misunderstood your suggestion. I thought that `yyset_lineno()` was to be called before `yyrestart()`. Putting it after, all is working fine.

**Pull request merged**
