### PR TITLE
CMake patches to fix the ninja builds on Windows

### PR DESCRIPTION
**Pull request by tlemo**
Fixes for #141

A couple of small changes to fix the Windows build when using the Ninja generator:
- the issue described in #141 
- adding missing source files (avx2/avx512bw)

Tested on Windows & Linux with make and ninja CMake generators.

### CODE REVIEW

**Comment by genivia-inc** [comment]
One question: shouldn't this addition be placed in `cmake` with extension .cmake instead of .txt?

**Comment by gahr** [comment]
CMake expects a CMakeLists.txt file

**Comment by gahr** [comment]
This generates a reflex_shared_lib.so and reflex_static_lib.a, which is pretty unusual on != Windows.

**Comment by tlemo** [comment]
> This generates a reflex_shared_lib.so and reflex_static_lib.a, which is pretty unusual on != Windows.

Hi @gahr, with these changes, the names are `libreflex_shared_lib.so` and `libreflex_static_lib.a`. Both are conforming to the unix naming conventions, have you experienced any issues with the new names? (or is it the `shared_lib` and `static_lib` naming pattern that caught your attention?)

**Comment by gahr** [comment]
Yep, having static and shared library *not* share the same basename makes it inconvenient to lookup the correct library by suffix, i.e. switch from shared to static by searching .a beforw .so. I’ve never seen this before to be honest.

**Comment by tlemo** [comment]
I'd like to understand the inconvenience part a bit better. If you're using reflex as a CMake subproject, you'd use `target_link_libraries` to link against the reflex libraries:

`target_link_libraries(my_target PRIVATE ReflexLib)`

Or to select the static version:

`target_link_libraries(my_target PRIVATE ReflexLibStatic)`

This has not changed in any way, both before and after the PR you'd have to pick the library flavor (`ReflexLib` or `ReflexLibStatic`) and the actual library file names are not relevant.

If you have a different kind of setup, I can see how a setup where both the '.a' and the '.so' have the same base name and you'd use something like `-static' (or '-Bstatic` for ld) to pick the intended flavor. Either way you'd need something in the build script to select the right version, and I don't see how a switch vs. different library base name is significantly more difficult.

**Comment by gahr** [comment]
I don’t source reflex as a subproject, I locate it - and other dependencies of mine - via `find_library`. I can typically switch between static and shared libraries with `CMAKE_FIND_LIBRARY_SUFFIXES`. The assumption here is that libraries have the same basename and a different extension. I would dare to say this is established practice on unid. I have never seen listing different names for dependencies’ libraries for the shared and static use case.

**Comment by tlemo** [comment]
Hi @gahr , my apologies for the delayed response.

I'm not sure if sharing the basename and building both shared and static versions of the same library is established practice with CMake though (yes, on Linux and a few other systems it's common to see _system wide_ libraries with the `.a` and `.so` next to each other, but that's a platform specific thing, not a portable, or perfect, solution)

With CMake, static and dynamic (shared) libraries normally come with separate targets, which by default implies different basenames. You'd have to go out of your way to force the same base name (which is what Reflex did, and as #141 shows, this is problematic).

Using `CMAKE_FIND_LIBRARY_SUFFIXES` to select the library version feels like a hack to me (not only that it's not cross-platform-friendly, but it has a number of pitfalls, for example conflicts with compiler/linker switches like `--static`). I'd recommend importing `reflex` as a subproject. If that's not an option, selecting the full library name should not be significantly more involved than tweaking `CMAKE_FIND_LIBRARY_SUFFIXES`.

**Comment by gahr** [comment]
Hi @tlemo , thanks for the detailed answer.

I can certainly vendor in re-flex in my projects, but I am here mostly as the maintainer of a re-flex port for FreeBSD.

It looks to me like the previous situation was better from a consumption standpoint except for the technical difficulty on Windows. Indeed, if it wasn't for the latter, we would still be in the former best situation. It seems like you are now trying to rationalize why having two different basenames is better even on non Windows platforms. I don't agree with your rationale, but I can accept an opinion different than mine. However, the version that introduces this change is not backwards compatible, so what is a downstream maintainer supposed to do? Should I track all ports that depend on re-flex and change how they pick the re-flex libraries, or should I patch re-flex so it behaves like before on FreeBSD, thus deviating from upstream?

Perhaps what I'll do is make sure nobody depends on the static library, and just install *one* flavour as libreflex.so.

**Comment by tlemo** [comment]
Ah, I'm starting to understand your context a bit better, thanks (btw, I love FreeBSD - thanks for your contribution!)

If I'm not wrong, the FreeBSD ports is based on makefiles - I imagine you have a makefile wrapping the CMake reflex build? If that's the case, wouldn't it be possible to copy/rename lib files as you wish in a post-build rule?

**Comment by gahr** [comment]
> wouldn't it be possible to copy/rename lib files as you wish in a post-build rule?

Yes, I can do that. However, that would mean re-flex libraries are named differently on vanilla re-flex and FreeBSD, which in turn means users of re-flex need to be patched on FreeBSD.

Do you think there's a real downside in having both .a and .so share the same basename on *nix? I.e., would anybody come up and this this change was a good idea if it wasn't for Windows?

**Pull request merged**
