### PR TITLE
Converted build system to autotools for unix-like systems.

### PR DESCRIPTION
**Pull request by tegtmeye**
Changes include:
  Headers and libraries are now properly named and installed as-per typical
  guidelines for unix-like systems.

  Bootstraps unicode support by building reflex twice, once to generate the
  unicode scripts and another to include them.

  Added support for common configure options.

  Added Doxygen and manfile generation.

  Parallel builds and distributions now work.

Limitations:
  Examples and tests are not-yet integrated

  Limited testing on common platforms

  Generated documentaton does not check for needed utilities like
  dot (Graphviz).

  Boost support has not been tested

  Build support for non-unix-like systems has not been touched.

  Some files have been renamed or moved to better support the build process.

Many support files typically generated by automake are no longer being tracked
in the repository as per common practice. This has the following implications:
If cloning/pulling directly from a git repository, you will need a recent
version of automake etc and must execute:

  autoreconf -fi

before attempting to run configure. Distribution tarballs are supported however
so after configuring and building, executing:

  make dist

will compile a complete distribution that can be configured immediately upon
extraction.

There are likely kinks that need to be worked out. Feedback welcome.

### CODE REVIEW

**Comment by tegtmeye** [comment]
As a quick note... Any new files that were created as part of this exercise have a BSD 3-clause added to the top with my name on it. If you want your licensing arranged differently, I'm OK with that. I just wanted to make it clear my contributions are also permissive.

**Comment by tegtmeye** [comment]
I just saw that builds were failing on Travis. I think I know the reason why. I think I'm missing the include in `bootstrap/Makefile.am` but I need to get to my linux machines at the office to test before I push.

```
bootstrap_reflex_CPPFLAGS= \
  -Wall -Wextra \
  -I$(top_srcdir)/include
```

**Comment by tegtmeye** [comment]
I'm adjusting the build and merging the update. Hopefully I'll have an updated merge request for interested parties to look at. I fixed the issue that was causing build failures but distributions were failing for a new reason on later version of Automake. The core issue is the bootstrapping process otherwise this would be straightforward.

The bottom line is that the choices are:

1. Keep the same overall source structure (lib, src,include,bootstrap,unicode, etc), incorporate automatic bootstrapping, and live with a bunch of Automake warnings about future incompatibilities regarding 'subdir-objects'. If Automake changes its behavior in future versions, this will likely break the build.

2. Keep the same overall source structure and do not include automatic bootstrapping per se. The package would look for a preinstalled version of reflex to generate the unicode files if it exists and use a stub otherwise. The downside of this is that building reflex to work as expected is a two step process and likely annoying to users and contributors pulling from the repository as it would be easy to get the unicode handling functions out of sync.

3. Change the code structure such that all sources sit in one directory and create a monolithic Makefile. The good news here is that automatic bootstrapping would work as expected and sources would only need to be compiled once rather than multiple times in option 1 & 2. The downside is the monolithic Makefile.am which some do not prefer (although others strongly feel that it is the correct way of setting up your build system. See [Recursive Make Considered Harmful](aegis.sourceforge.net/auug97.pdf) ). In any case though, the Makefile.am definitely gets more complex.

In any of these cases, library and header installation should work per standard GNU/unix-like system guidelines

At the moment I'm in favor of option 3. I hopefully will be able to finish up tonight and get it committed for consideration by others.

**Comment by genivia-inc** [comment]
Some suggestions on your last comment:

I also can't remove the automake warnings regarding `subdir-objects` on my system. I tried that before, but it breaks automake. Perhaps an issue with the version(s) I could successfully install on Mac OS. I have the same problem with other projects I'm running.

With respect to automatic bootstrapping, I did not do this because a compilation error may lead to incomplete files being generated and you're completely stuck. That's why I added a `bootstrap.sh` script to generate the files only when needed manually, i.e. when the Unicode specs are updated.

So I prefer to keep the automake files as they are. There are perhaps some improvements for `configure.ac` and the  localized `Makefile.am` to consider.

**Comment by tegtmeye** [comment]
Although I could end up eating my words, I'm somewhat confident that I've got the dependancies set up appropriately such that a compilation error won't cause you to end up with an incomplete file being generated in the base of bootstrapping the unicode content.

Looking at the existing build, moving to a more standard autotoolized version (autoconf, Automake, Libtool, etc) would probably benefit users IMHO. I won't be able to do anything with it until tonight but since I'm about 98% of the way into completing option (3) above, I'll finish it if nothing more than to give you something to draw from.

**Comment by genivia-inc** [comment]
Great.

**Comment by tegtmeye** [comment]
OK, I haven't merged your recent changes but you can pull from the 'libtoolize' branch of my fork if you want to have a look and play around. Appears to build and work properly. There are a couple of things worth improving but it would likely be unnoticeable to end users. I'll merge your latest release tomorrow so at least you are looking at an apple to apples comparison.

**Comment by tegtmeye** [comment]
OK. Added the tests directory back using the "make check" functionality that comes with Automake. I saw that you had hardcoded .dylibs in the existing makefile so this should fix that. I also renamed the included '.cpp' files as Automake will generally not like that if you add it into its automatic dependency tracking. I just renamed them to '.h's since they would only ever get included once. Parallel checks (ie make -j check) works as well. Well sort of...

On my Mac, the lorem tests appears to infinite loop on the std::regex portion. Maybe I am just not patient enough and it is just really slow though... I remove the target so that the checks would continue.

On my ubuntu machine, the 'stest' fails for 'find results'.


Lastly, I'm not too familiar with Travis but the CI failures appear to be because it is trying to run 'make test' rather than the standard Automake 'make check' targets. I could add a thunk target but not sure if there is some setting on your end that causes it to look for tests and not check.

I bumped the library and package version to reflect your v1.1.2. 

Lastly, if you merge anything, make sure you change the AC_INIT[...]. The link references my repo so it doesn't look like like mine is posing as coming from your official repository.

**Comment by genivia-inc** [comment]
I noticed that the `std::regex` library appears broken (or its API is not well documented) with respect to iterators, giving random behaviors in some cases. This is surprising because the `std::regex` library is a simpler reflection of the `boost::regex` library, but apparently the regex iterator state is not consistent (compared to boost).

That's why I removed it from `Makefile.am` but kept it in `Make` though I should have removed it there too, until we can fix this problem.

The `std::regex` library is extremely slow. So I can't see any justification to use it at this point.

**Comment by genivia-inc** [comment]
My comments. I have some more, but here is a start:

`.gitignore` is OK. However, there is a `reflex-*.tar.gz` specified, but the tarball is actually not a consistent name but depends on the distro downloaded, e.g. SourceForge, GitHub, or Homebrew. These use different file names. So `reflex-*.tar.gz` should not be specified.

The `Makefile.am` contain license texts, but that is very unusual for these type of files to list the full license. Installation scripts should be kept clean.

Do not remove `man1_MANS` from `Makefile.am`.

I do not recommend to have a `doc/Makefile.am` for running Doxygen and rename `doc/Doxyfile.in`.

Rather, there are more direct ways to do this. Check if Doxygen is present in `configure.ac` and then define in the main `Makefile.am` the rules, for example:

~~~
# Generate library documentation using Doxygen.
# If it's not available, just touch a stamp file in the right directory.
# The configure.ac sets DOXYGEN to NO_DOXYGEN if it's not found.
libdocdir = @DOXYGEN_OUTPUT_DIRECTORY@
DOXYGEN=@DOXYGEN@
$(libdocdir): Doxyfile
	if test -d $(libdocdir); then \
	  rm -Rf $(libdocdir); \
	fi
	if test "$(DOXYGEN)" != NO_DOXYGEN; then \
	  $(DOXYGEN); \
	else \
	  mkdir $(libdocdir); \
	  echo "No doxygen available -- library documentation not generated" >$(libdocdir)/stamp; \
	fi
~~~

Do not specify `HAVE_DOXYGEN` and `MAYBE_DOCS`.

There is a better way to include the examples in the build process. I will write up a `configure.ac` like I’ve done in other projects that checks for option `--enable-examples` to generate the examples. Adding more options like this is best, e.g. to build Bison and Boost-related examples which require Bison and Boost. That would be useful additions, because we don't want the builds to fail when Bison or Boost are not installed.

The test cases should still be included by building `rtest` and perhaps `btest` if Boost is installed which is just checking with `HAVE_BOOST_REGEX` (I presume, but I need to check), with the addition of `AX_BOOST_REGEX` to `configure.ac`.

We need to keep `AC_INIT(… 1.1)` instead of 1.1.2. I used `sed` to change the version number as part of my `makemake.sh` script (which I didn't share yet in the repo), but I found that changing `configure.ac` causes trouble with `aclocal.m4` (reruns in a loop). For now, the major-minor version ID is manually changed.

That's it for now.

**Comment by genivia-inc** [comment]
I've rewritten `configure.ac` and the `Makefile.am` in my local dev branch to be able to generate the documentation on demand with `make doc/html`. The examples are build with `./configure --enable-examples; make`. I will release these updates today.

Unfortunately I couldn't use your `configure.ac` or `Makefile.am` files because they don't work in my Mac. Also `AX_BOOST_BASE` and `AX_BOOST_REGEX` are not widely supported and actually not used in the `Makefile.am`. Therefore, I restricted the build to assume Boost is not installed, which means that only the `rtest` is built and the non-Boost examples are built. Just execute `make boostexamples` in `reflex/examples` to get these compiled.

It is not good to be overly ambitious to try to add everything in a single build step. My experience is that people get frustrated and quickly give up when something does not build because of missing or outdated dependencies. I wanted reflex to have as few dependencies as possible.

**Comment by tegtmeye** [comment]
I spent some time reworking a few things last night before I saw your comments so some of the below is likely moot.

> .gitignore is OK. However, there is a reflex-*.tar.gz specified, but the tarball is actually not a consistent name but depends on the distro downloaded, e.g. SourceForge, GitHub, or Homebrew. These use different file names. So reflex-*.tar.gz should not be specified.

The `reflex-*.tar.gz` in .gitignore is not intended for the distro outlet (ie sourceforge, homebrew, etc) It is an artifact of distribution generation ie `make dist` and `make distcheck` as well as tar-ing up the html documentation for installation. This file should never be included in the repository but if you don't mind it showing up as an untracked file every time you run `git status`, I can take it out.

> The Makefile.am contain license texts, but that is very unusual for these type of files to list the full license. Installation scripts should be kept clean.

I'm not sure that is a universal statement. Many, many projects have the license as part of the `Makefile.am` including Automake itself. In fact many groups (certainly GNU) specifically request that you include the license at the top of each file (see https://opensource.org/faq#apply-license) in the end, it is a personal preference whether you choose to include the license at the top of each non-tool generated file or just reference the top level license. If you would prefer it not to be there, I'm happy to take it back out. However, a `Makefile.am` is generated by a person and copyright applies to it just as much as it applies to a source file.  As a word of caution, some corners of the open source community take a very hard line on what they view is ambiguous copyright--meaning that claims of copyright get difficult fast if the `Makefile.am` (or any other user-generated file) gets separated from the rest of the distro and modified by a third party.

> I do not recommend to have a doc/Makefile.am for running Doxygen and rename doc/Doxyfile.in.

I generally don't include Doxygen much in my projects anymore so it would be great if you have a newer, better solution. What Included is what I used before and is almost verbatim from the Autotools book from Calcote. Ultimately what I think is important is that the documentation only gets rebuilt when needed (rather than always), it gets installed in the correct location ($docdir), and building the Doxygen source reflects the build environment. The latter is why I used `Doxyfile.in`, so that configure can turn off `dot` support if Graphviz is not available for example.

> Do not remove man1_MANS from Makefile.am

I moved man1_MANS to `src/Makefile.am` to solve a dependency problem that exists in the original setup. Basically, manfile generation depends on the fully functioning version of reflex meaning that if the build reflex changes in any way, the manfile should be rebuilt. Putting it into the top-level `Makefile.am` and setting up the dependancies into another directory probably can be done but the rule that runs `man.sh` got ugly fast. Speaking of `man.sh`, is there an aversion to using help2man (https://www.gnu.org/software/help2man) for this?

`There is a better way to include the examples in the build process...`

Working with the examples is what I spend some time on last night. Generally speaking, I agree with having the ability to selectively configure examples but there is a bigger, more philosophical issue in play here. This issue is compounded by the historical audience for things like lexers/parser (ie students). I'm not really talking about the example source but rather the build process.

To me, examples are training wheels for new users. New users in this sense can be _really_ new users (ie students who don't even know what a lexer is) but also can be experienced developers who just want to get up to speed fast on how to use your package. This fact means that the build process is in conflict. 

To the developer of the package (ie you), you want to ensure your examples build and run correctly for the various installation systems you want to support. In this scenario, you want the examples to build and link against your _working_ copy of reflex (ie the built libreflex and reflex executable buried in your source tree), you want the build to reflect the results of the tests that configure runs, and you want to be able to disable it if necessary.

In my mind, this is different than what gets installed. The examples that get installed need a simple makefile that does not depend on how the package was configured or the internals of the package developers build system.  As an example of what I mean, you wan't want the installed example Makefile to disable the Boost examples because a user installed reflex before Boost using Homebrew. In my experience, good installed examples are intended to be copied to a users home directory somewhere and make an assumption of a sane build environment and properly set up paths (bin, include, lib) with the ability to customize the details for the sake of concise, easy to understand Makefile. This is not unlike what you currently have.

The straightforward way to meet the previous two objectives is to have two example build systems (ie two Makefiles) but that is also problematic. Two Makefiles need to be maintained and can get out of sync (the current example Makefiles in your tip are out of sync BTW. `flexexample10` and another one if I remember correctly). I was trying something new where there is a common Makefile.in.in that gets build by configure into a maintainer-specific Makefile and a simpler installed Makefile. I'm mostly done but it hasn't been looked at critically yet though.

`The test cases should still be included by building rtest and perhaps btest`

OK, I'll add them back into tests with skip and expected fail. I agree it should reflect the status of Boost as well. I just wan't sure that I was messing something up since it was failing and appeared to be in an infinite loop.

`We need to keep AC_INIT(… 1.1) instead of 1.1.2`

OK. I only bumped it because it reflected your 1.1.2 modifications. In my experience, I think most people leave this alone until they are ready to actually do a release. As an aside, I wouldn't put aclocal into the repository. At best it gets rewritten as soon as someone checks out the repo and builds it and at worse causes problems. The same goes for the docs because each commit will contain dozens to hundreds of changes to files with nothing more than the date changing reflecting when Doxygen was run.

In my experience, good packages adopt the following philosophy:

1. What is in the git repository is intended for package maintainers and distributers. That is, there is an expectation that you will need external programs and utilities to build the package. For example, Automake, Autoconf, Libtool, Doxygen, help2man, etc. Only store in the repository what can't be automatically generated by having these tools. The guidance to folks checking the package out of git should be: have the list of tools installed in your build environment, issue `autoreconf -fi`, run `configure ..`, and then `make` and friends. If you make changes, make sure `make -j distcheck` passes (preferably before committing). To make a distribution for say, a release download, run `make dist` to build a distribution tarball. I believe this lines up with GNU's best practices but I suspect others as well.

2. What is distributed (ie the distribution tarball) should NOT depend on anything other than `make` and the project-specific dependancies. For example Boost. All users need to do is make sure the project-specific dependancies are available to the build environment and then `./configure ..` and then `make && make install`. Since documentation was generated and stored in the tarball in step 1 above, things like Doxygen, help2man, and Graphviz are not needed on the installation machine.

In the end, this is your project. I've been wanting to see a Flex replacement for some time now so I'm happy to provide help where I can.

**Comment by tegtmeye** [comment]
So I don't have a change to read your last reply before I finished my comment.

AX_BOOST_BASE and AX_BOOST_REGEX are from the autoconf-archive (https://www.gnu.org/software/autoconf-archive/) and I've never run into issues using it on my Mac or any of the major linux distros. I don't know if you are targeting something more exotic though.

**Comment by genivia-inc** [comment]
One more issue: `.gitignore` specified `config.h*` which does not allow pushing `config.h.in` up to the repository. This breaks the last configure step.

**Comment by tegtmeye** [comment]
Being included in a .gitignore does not prevent a file from existing in a repository, it simply means that it doesn't get flagged for changes, for example when running `git status` (https://git-scm.com/docs/gitignore). Having config.h.in is typically included as being ignored for autotoolized builds. Here is a list of common .gitignore templates that people typically start from when creating new projects (https://github.com/github/gitignore). I believe these templates are published by GitHub itself.

Why are you storing `config.h.in` in the repository?  There is nothing in the current `config.h.in` that is not automatically created by configure? In fact, quickly looking at your sources, nothing is including config.h anyway.

I suspect that because you are running into issues with things like aclocal and config.h.in means that you are fighting autoconf, automake, etc in the context of git repositories. I'd really recommend taking a mainstream approach to the build system. Autotools are not for everyone but whatever tool you use, consider using it as its intended unless you really _need_ to do something clever. There is a lot of wisdom wrapped up in the autotool build system and plenty of documentation on how to use it correctly.

**Comment by genivia-inc** [comment]
`config.h.in` should be pushed when changed as `./configure` needs this. Before each release I run `autoheader`, `aclocal`, `automake`, `autoconf` to keep things tidy and up to date, using my `makemake.sh` script. If `config.h.in` changes for whatever reason, it should find its way upstream. My scripts also clean the repository before commit and push, so for example`.gitignore` isn't really needed and I view this as extra junk for lazy folks who don't clean their local repos before commit and push. My script preps release packages cleanly for both SourceForge release and GitHub. It is all turn-key automated on my side. The only thing I wish for is `sed "s/AC_INIT(reflex,[^)]*)/AC_INIT(reflex,$1)/" configure.ac > configure.tmp && mv -f configure.tmp configure.ac` to work with GitHub, but alas with this git saves `configure.ac` as new causing trouble with `aclocal.m4` requiring users to run `autoreconf -fi` every time before `./configure`. With 20 years of experience with this stuff I rather do things with bash and not rely on tool-specific stuff (such as `.gitignore`) that may be outdated in a couple of years when Git is replaced by something new.

**Comment by tegtmeye** [comment]
I also have about three decades of experience here and you are certainly entitled to your own preferences on how you maintain your own repository. While I would have bought off on some of your workflow ten years ago or so, I have to say you are really swimming upstream here. autoreconf was specifically designed to run the appropriate tools in-order prior to configuring a bare repository to take platform-specific nuances out of the equation and it is many years old at this point. Likewise, I think it is pretty safe to say git is beyond a passing fad. Generally speaking, everything that I am suggesting and commenting on is directly out of the automake/autoconf documentation.

As I said, I very much would like to see a flex replacement. I _want_ to see you succeed here. Success means buy-in from other developers though. Part of the buy-in comes from infrastructure commonality. Running contrary to many established best practices with a toolchain that is either only available or understood by you or eschews the most common open source development principles because you claim the tools are not trustworthy or that people that use them are lazy may not be the best strategy in getting that buy-in.

**Comment by genivia-inc** [comment]
The `.gitignore` I have is:

~~~
# Minimalistic .gitignore
#
# Project contributors: clean with ./clean.sh, do not rely on .gitignore

# Object files
*.o
*.os
*.ko
*.obj
*.elf

# Precompiled Headers
*.gch
*.pch

# Libraries
*.lib
*.a
*.la
*.lo
*.def
*.exp

# Shared objects (inc. Windows DLLs)
*.dll
*.so
*.so.*
*.dylib

# Logs
*.log

# Executables
a.out

# Autotools
Makefile
config.h
config.status
config.log
stamp-h
~~~

The `clean.sh` script should be extended with this line:

~~~
rm -f Makefile config.h config.status config.log stamp-h1
~~~

Again, I see issues with the proposed `configure.ac` and `Makefile.am` files in the pull request. The ones I updated in the 1.1.3 release now work reliably on Mac and the four different Linux distros I use for testing. I also found a better approach to run Doxygen, by searching for the Doxygen Application on Mac OS since most folks will have the Desktop version installed rather than the doxygen CLI. I also added configure option `--enable-examples` similar to yours, which I had to make sure builds the non-Boost and non-Bison-3.0 examples (`AX_BOOST_REGEX` does not reliably work). This is not a big deal. The examples are meant to enhance comprehension of the tools and lexer specs, not to provide a core functionality to the toolchain.

Autotools are great, but highly overrated in some sense. These were a must-use years ago. But as C++ has matured, building projects with standard Makefiles isn't much of an issue any longer, or should not be, unless lower-level library APIs are used. Sure, we still need autoconf and automake with package managers, no doubt. No KISS reward for that though. And no, I don't want to go back to the time I had to use Basic, Pascal and Fortran in the early 80s. But back then I enjoyed the ABC language that we used as "guinea pigs" back in the Netherlands, from CWI, which influenced Python.

**Comment by genivia-inc** [comment]
Your contributions are really appreciated, but I also really wanted to keep the auto scripts clean and simple and was pleased with the few lines it took to complete `configure.ac` months ago. There should be none or few dependencies as possible. Since RE/flex doesn't depend on Boost, Bison, or C++11 `std::regex` we should not require (breakable) rules to build more examples than necessary.

**Pull request closed without merging**
